# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  schedule:
    - cron: 0 12 * * *
  workflow_dispatch:
    inputs:
      tags:
        description: 'Start!!!'

jobs:
  job1:
    name: workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: prepare python environment(v3.11)
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: execute
        id: execute
        run: |
          python main.py

      - name: pull
        run: |
          git checkout .
          git pull --allow-unrelated-histories

      - name: keep alive
        uses: Smart-Transportation/push@v1.3
        continue-on-error: true
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: 'main'
          author_email: '1295053522@qq.com'
          author_name: 'jaychouncf'
          message: '🐳 chore: keep action alive'
